export const PROTOCOL_CONFIG = {
  NAME: "PLANTD",
  TOKEN_SYMBOL: "PLANTD",
  NATIVE_TOKEN: "SOL",
  MIN_STAKE: 0.1,
  MAX_STAKE: 10000,
  CONVERSION_RATE: 2, // 1 SOL = 2 $PLANTD
  DEFAULT_LOCK_PERIOD: 7, // days
  DEFAULT_APR: 12,
} as const;
